# Generated by Django 5.1.6 on 2025-02-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(to="orders.item"),
        ),
    ]
