# Generated by Django 5.1.6 on 2025-02-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_items_order_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="item_images/"),
        ),
        migrations.AddField(
            model_name="order",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="order_images/"),
        ),
    ]
