# Generated by Django 5.1.6 on 2025-02-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_item_image_order_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="image",
        ),
    ]
